# DATA WRANGLING

In [1]:
from googleapiclient.discovery import build
import pandas as pd
import time
import csv

In [2]:
# Masukkan API Key YouTube Data API v3 kamu di sini
api_key = 'AIzaSyBfjWQ8nDZgiu3P-0WiRLXJV2hm5rif848'

# Menghubungkan ke YouTube API menggunakan developer key
youtube = build('youtube', 'v3', developerKey=api_key)

def get_youtube_comments(video_id, max_comments):
    comments_data = []
    next_page_token = None
    
    # Looping untuk mengambil data sampai mencapai target (contoh: 15.000)
    while len(comments_data) < max_comments:
            # Memanggil API untuk mendapatkan komentar
            request = youtube.commentThreads().list(
                part="snippet",
                videoId=video_id,
                maxResults=1000, # Batas maksimal dari YouTube per request
                pageToken=next_page_token,
                textFormat="plainText"
            )
            response = request.execute()

            # Mengekstrak data komentar yang relevan
            for item in response.get('items', []):
                if len(comments_data) >=  max_comments:
                    break
                comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
                author = item['snippet']['topLevelComment']['snippet']['authorDisplayName']
                like_count = item['snippet']['topLevelComment']['snippet']['likeCount']
                published_at = item['snippet']['topLevelComment']['snippet']['publishedAt']
                comments_data.append({
                    'author' : author,
                    'comment' : comment,
                    'likes' : like_count,
                    'published_at' : published_at
                })
                
                # Mengecek apakah ada halaman/komentar selanjutnya
                next_page_token = response.get('nextPageToken')
                if not next_page_token :
                    break # Berhenti jika semua komentar sudah diambil

    return comments_data [:max_comments]

# Buat menyimpan files komentar menjadi CSV
def save_comments_to_csv(comments_data, filename):
    with open(filename, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.DictWriter(file, fieldnames=['author','comment','likes','published_at'])
        writer.writeheader()
        writer.writerows(comments_data)

# Fungsi utama untuk mengambil komentar dari video
def scrape_comments_from_videos(video_ids, total_comments, output_filename):
    all_comments = []
    comments_per_video = total_comments // len(video_ids)

    for video_id in video_ids:
        comments = get_youtube_comments(video_id, comments_per_video)
        all_comments.extend(comments)
    
    if len(all_comments) < total_comments:
        extra_comments = total_comments - len(all_comments)
        extra_comments_from_first = get_youtube_comments(video_ids[0], extra_comments)
        all_comments.extend(extra_comments_from_first[:extra_comments])

    # Simpan ke CSV
    save_comments_to_csv(all_comments, output_filename)
    return all_comments

In [3]:
# ID Youtube
video_ids = ['B_8A2vDfyF4']

total_comments = 4396
output_filename = 'file_comments.csv'

# Mengambil komentar 
comments = scrape_comments_from_videos(video_ids, total_comments, output_filename)

df = pd.DataFrame(comments)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 4396 entries, 0 to 4395
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        4396 non-null   str
 1   comment       4396 non-null   str
 2   likes         4396 non-null   int64
 3   published_at  4396 non-null   str
dtypes: int64(1), str(3)
memory usage: 137.5 KB

,author,comment,likes,published_at
0,@tohasukirman6296,"Yah Presiden sekarang cuman omon2, daan tdk p...",0,2026-05-14T02:25:58Z
1,@F41zal,Mantap...Memang negara ini milik kita bersama....,0,2026-05-13T23:01:14Z
2,@SriMul-d1c9i,Peristiwa 1998 bisa mungkin terjadi,0,2026-05-13T08:42:37Z
3,@asriodeteke2783,Berpotensi untuk terulangnya tragedi 1998.\nMu...,0,2026-05-13T02:09:13Z
4,@Mama-f8z,"Magput ini SDH kadaluarsa, jdi gak perlu byk o...",0,2026-05-13T02:07:46Z

## DATA PREPROSESSING

In [4]:
data = pd.read_csv('file_comments.csv')
data.info()
data.head()

<class 'pandas.DataFrame'>
RangeIndex: 4396 entries, 0 to 4395
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        4396 non-null   str
 1   comment       4396 non-null   str
 2   likes         4396 non-null   int64
 3   published_at  4396 non-null   str
dtypes: int64(1), str(3)
memory usage: 137.5 KB

,author,comment,likes,published_at
0,@tohasukirman6296,"Yah Presiden sekarang cuman omon2, daan tdk p...",0,2026-05-14T02:25:58Z
1,@F41zal,Mantap...Memang negara ini milik kita bersama....,0,2026-05-13T23:01:14Z
2,@SriMul-d1c9i,Peristiwa 1998 bisa mungkin terjadi,0,2026-05-13T08:42:37Z
3,@asriodeteke2783,Berpotensi untuk terulangnya tragedi 1998.\nMu...,0,2026-05-13T02:09:13Z
4,@Mama-f8z,"Magput ini SDH kadaluarsa, jdi gak perlu byk o...",0,2026-05-13T02:07:46Z

In [7]:
data['published_at'] = pd.to_datetime(data['published_at'])

data['date'] = data['published_at'].dt.time
data['time'] = data['published_at'].dt.time

data.head()

,author,comment,likes,published_at,date,time
0,@tohasukirman6296,"Yah Presiden sekarang cuman omon2, daan tdk p...",0,2026-05-14 02:25:58+00:00,02:25:58,02:25:58
1,@F41zal,Mantap...Memang negara ini milik kita bersama....,0,2026-05-13 23:01:14+00:00,23:01:14,23:01:14
2,@SriMul-d1c9i,Peristiwa 1998 bisa mungkin terjadi,0,2026-05-13 08:42:37+00:00,08:42:37,08:42:37
3,@asriodeteke2783,Berpotensi untuk terulangnya tragedi 1998.\nMu...,0,2026-05-13 02:09:13+00:00,02:09:13,02:09:13
4,@Mama-f8z,"Magput ini SDH kadaluarsa, jdi gak perlu byk o...",0,2026-05-13 02:07:46+00:00,02:07:46,02:07:46